#!/bin/bash

# ralph-maintenance.sh - Autonomous codebase maintenance and cleanup
# Identifies AND FIXES code quality issues in pretorin-cli, one task per iteration.
#
# Usage:
#   ./scripts/ralph-maintenance.sh

set -e

CHECKLIST_FILE="maintenance-checklist.md"
LOG_DIR="logs/maintenance"
mkdir -p "$LOG_DIR"

# Resume logic - check if we have an existing checklist with incomplete tasks
if [ -f "$CHECKLIST_FILE" ]; then
  if grep -q "^\- \[ \]" "$CHECKLIST_FILE" && ! grep -q "ALL_TASKS_DONE" "$CHECKLIST_FILE"; then
    EXISTING_BRANCH=$(git branch --show-current)
    if [[ "$EXISTING_BRANCH" == maintenance/* ]]; then
      echo "Resuming maintenance on existing branch: $EXISTING_BRANCH"
      BRANCH_NAME="$EXISTING_BRANCH"
      LOG_FILE="$LOG_DIR/$(echo $BRANCH_NAME | tr '/' '-').log"
      echo ""
      echo "=== Resuming at $(date) ===" >> "$LOG_FILE"
    else
      echo "Found incomplete checklist but not on maintenance branch."
      echo "Options:"
      echo "  1) Delete $CHECKLIST_FILE and start fresh"
      echo "  2) Checkout the maintenance branch and re-run"
      exit 1
    fi
  else
    rm -f "$CHECKLIST_FILE"
    BRANCH_NAME="maintenance/$(date +%Y%m%d-%H%M%S)"
    LOG_FILE="$LOG_DIR/$(echo $BRANCH_NAME | tr '/' '-').log"
    git checkout -b "$BRANCH_NAME"
    echo "Starting fresh maintenance on branch: $BRANCH_NAME"
    echo "=== Started at $(date) ===" > "$LOG_FILE"
  fi
else
  BRANCH_NAME="maintenance/$(date +%Y%m%d-%H%M%S)"
  LOG_FILE="$LOG_DIR/$(echo $BRANCH_NAME | tr '/' '-').log"
  git checkout -b "$BRANCH_NAME"
  echo "Starting maintenance on branch: $BRANCH_NAME"
  echo "=== Started at $(date) ===" > "$LOG_FILE"
fi

echo "Log file: $LOG_FILE"

# Initialize checklist if it doesn't exist
if [ ! -f "$CHECKLIST_FILE" ]; then
  cat > "$CHECKLIST_FILE" << 'EOF'
# Maintenance Checklist

This checklist drives automated maintenance for pretorin-cli. Each task should IDENTIFY and FIX issues.

## Phase 1: Analysis & Quick Fixes

- [ ] **1. CI Health Check** - Review recent GitHub Actions runs, identify existing failures to fix
- [ ] **2. Lint Fixes** - Run ruff check + format, auto-fix what's possible, document remaining issues
- [ ] **3. Type Check Fixes** - Run mypy, fix type errors in critical paths (client, MCP handlers, CLI)
- [ ] **4. TODO/FIXME Audit** - Catalog all TODO/FIXME comments, resolve quick ones, create issues for complex ones

## Phase 2: Test Quality

- [ ] **5. Test Coverage Analysis** - Identify files <60% coverage, write missing tests for critical code (client, attestation, MCP handlers)
- [ ] **6. Dead Test Cleanup** - Find and remove tests for deleted features/code, fix flaky tests

## Phase 3: Code Quality

- [ ] **7. Code Duplication Audit** - Find redundant utilities, similar handler patterns, copy-paste code across CLI/MCP/agent surfaces
- [ ] **8. Dead Code Removal** - Find unused imports, functions, models, CLI commands. Remove them.
- [ ] **9. Dependency Updates** - Check for outdated or vulnerable dependencies, update safe ones, document risky ones

## Phase 4: Release & Config Health

- [ ] **10. Version Consistency** - Verify pyproject.toml version == __init__.py __version__ == CHANGELOG.md latest heading. Fix drift.
- [ ] **11. MCP Tool Registration Audit** - Verify every Tool in tools.py has a handler in __init__.py and vice versa. Flag orphans.
- [ ] **12. Agent Skill Tool Coverage** - Verify agent skills reference tools that actually exist in agent/tools.py. Flag stale references.

## Phase 5: Wrap-up

- [ ] **13. Local Verification** - Run `./scripts/check.sh` locally (lint, typecheck, all tests). If it passes, mark complete. Do NOT push, create a PR, or run CI — the outer script handles that.

## Progress Log

EOF
  echo "Created $CHECKLIST_FILE"
fi

echo ""
echo "Starting maintenance loop..."
echo "Checklist: $CHECKLIST_FILE"
echo "Branch: $BRANCH_NAME"
echo "Log: $LOG_FILE"
echo ""

# Log function - writes to both stdout and log file
log() {
  echo "$@" | tee -a "$LOG_FILE"
}

ITERATION=0
MAX_ITERATIONS=20  # Safety cap (13 tasks + buffer for retries)

while [ $ITERATION -lt $MAX_ITERATIONS ]; do
  ITERATION=$((ITERATION + 1))
  log ""
  log "=== Iteration $ITERATION of $MAX_ITERATIONS at $(date) ==="

  # Check if all tasks complete
  if grep -q "ALL_TASKS_DONE" "$CHECKLIST_FILE" 2>/dev/null; then
    log ""
    log "All maintenance tasks complete!"
    log "Pushing branch and creating PR..."
    git push -u origin "$BRANCH_NAME"

    gh pr create --title "Maintenance: Automated code quality improvements" --body "$(cat <<'PREOF'
## Automated Maintenance

This PR contains automated code quality improvements generated by `ralph-maintenance.sh`.

### Changes Include:
- Lint and type check fixes
- Test coverage improvements
- Dead code removal
- Code duplication refactoring
- Version and registration consistency fixes

### Review Notes:
- Each fix was committed separately for easy review
- See `maintenance-checklist.md` for detailed progress log
- All checks pass locally (`./scripts/check.sh`)

---
Generated by scripts/ralph-maintenance.sh
PREOF
)"
    log ""
    log "PR created. Review the changes on the branch: $BRANCH_NAME"
    log "=== Completed at $(date) ==="
    exit 0
  fi

  # Run Claude for one task, capturing output to log
  set +e
  OUTPUT=$(claude --dangerously-skip-permissions -p "@$CHECKLIST_FILE

You are a codebase maintenance engineer for pretorin-cli, a Python CLI and MCP server package. Your job is to IDENTIFY AND FIX issues, one task per iteration.

Branch: $BRANCH_NAME

CRITICAL: Complete exactly ONE task, commit your fixes, then output <promise>DONE</promise> and stop.

## PROJECT CONTEXT

This is a Python package (src/pretorin/) with:
- CLI commands (typer) in src/pretorin/cli/
- MCP server tools in src/pretorin/mcp/ (tools.py defines tools, handlers/ dispatches them, __init__.py registers the mapping)
- Agent tools and skills in src/pretorin/agent/
- API client in src/pretorin/client/api.py
- Source attestation in src/pretorin/attestation.py
- Tests in tests/
- Docs in docs/src/ (mdBook source) and docs/CLI.md, docs/MCP.md (standalone)
- CI in .github/workflows/test.yml
- Local check script: ./scripts/check.sh

## TOOLS REFERENCE

**Linting & Types:**
- uv run ruff check src/pretorin --fix
- uv run ruff format src/pretorin
- uv run mypy src/pretorin

**Tests:**
- uv run pytest -v --cov=pretorin --cov-report=term-missing -q
- uv run pytest tests/test_specific_file.py -v

**Code Analysis:**
- grep -rn 'TODO\|FIXME' src/pretorin/ tests/ | head -50
- grep -rn 'import.*unused' src/pretorin/ (after ruff)

**Version Consistency:**
- grep 'version' pyproject.toml | head -3
- grep '__version__' src/pretorin/__init__.py
- head -20 CHANGELOG.md

**MCP Tool Registration:**
- grep 'name=\"pretorin_' src/pretorin/mcp/tools.py (all defined tools)
- grep 'pretorin_' src/pretorin/mcp/handlers/__init__.py (all registered handlers)

**Agent Skills:**
- grep -A 20 'tool_names' src/pretorin/agent/skills.py (tools referenced by skills)
- grep 'name=\"' src/pretorin/agent/tools.py (tools actually defined)

**Dependencies:**
- uv run pip-audit --skip-editable .
- uv pip list --outdated

**CI:**
- gh run list --limit 5
- gh run view <id> --log-failed

**Local Verification:**
- ./scripts/check.sh

## RULES

1. **DO ONE TASK ONLY** - Not two, not three, just ONE
2. **ACTUALLY FIX ISSUES** - Don't just report them. Write code, delete dead code, add tests
3. **COMMIT EACH FIX** - Use descriptive commit messages: \"fix(maintenance): <what was fixed>\"
4. **BE CONSERVATIVE** - If a fix is risky or unclear, note it in the checklist and skip
5. **RUN TESTS** - Before committing, verify your changes don't break things: uv run pytest -x -q
6. **UPDATE CHECKLIST** - Mark task [x] complete, add log entry with commit hash
7. **STOP AFTER ONE** - Output <promise>DONE</promise> and stop. Loop handles continuation.

## TASK-SPECIFIC GUIDANCE

**CI Health Check:** Run gh run list --limit 5. If failures exist, investigate with gh run view <id> --log-failed. Log findings.

**Lint Fixes:** Run uv run ruff check src/pretorin --fix && uv run ruff format src/pretorin. For remaining issues, fix manually if simple.

**Type Check Fixes:** Run uv run mypy src/pretorin. Focus on errors in client/, mcp/, cli/. Skip complex generic issues.

**TODO/FIXME:** Quick fixes (<10 lines): just do them. Complex ones: leave a note in checklist.

**Test Coverage:** Run uv run pytest --cov=pretorin --cov-report=term-missing -q. Focus on business logic (client, attestation, handlers). Write meaningful tests, not coverage padding.

**Dead Test Cleanup:** Look for tests referencing removed functions/classes. Remove them. Run tests after.

**Code Duplication:** Look for similar patterns across CLI/MCP/agent surfaces. Extract shared logic if it reduces maintenance burden.

**Dead Code:** Use ruff to find unused imports. Search for functions/classes not referenced elsewhere. Remove and test.

**Dependency Updates:** Run uv run pip-audit --skip-editable . for vulnerabilities. Check uv pip list --outdated for updates. Only update safe ones.

**Version Consistency:** Compare pyproject.toml version, __init__.py __version__, and CHANGELOG.md latest heading. All must match.

**MCP Tool Registration:** Compare tool names in tools.py vs handler keys in handlers/__init__.py. Every tool needs a handler and vice versa.

**Agent Skill Tool Coverage:** Compare tool_names lists in skills.py against actual tool definitions in agent/tools.py. Flag references to nonexistent tools.

**Local Verification:** Run ./scripts/check.sh. Fix any failures caused by our changes.

## WORKFLOW

1. Read checklist, find first unchecked [ ] task
2. Run analysis commands
3. Make fixes (edit files, write tests, delete dead code)
4. Run relevant tests to verify
5. Commit with descriptive message
6. Update checklist: mark [x], add log entry with timestamp + commit hash
7. Output <promise>DONE</promise>
8. STOP IMMEDIATELY

When ALL tasks are [x] complete, add 'ALL_TASKS_DONE' at the end of the checklist.")
  CLAUDE_EXIT_CODE=$?
  set -e

  echo "$OUTPUT" | tee -a "$LOG_FILE"

  if [ $CLAUDE_EXIT_CODE -ne 0 ]; then
    log ""
    log "WARNING: Claude command exited with code $CLAUDE_EXIT_CODE"
    if grep -q "ALL_TASKS_DONE" "$CHECKLIST_FILE" 2>/dev/null; then
      log "Tasks are complete despite error. Proceeding with PR creation..."
      continue
    fi
    log "Waiting before retry..."
    sleep 5
    continue
  fi

  if echo "$OUTPUT" | grep -q "<promise>DONE</promise>"; then
    log ""
    log "--- Task completed, restarting with fresh context ---"
  else
    log ""
    log "WARNING: No completion marker found"
  fi

  sleep 2
done

log ""
log "Reached max iterations ($MAX_ITERATIONS)."
log "Check $CHECKLIST_FILE for remaining tasks."
log "You can continue manually or re-run the script to resume."
log "=== Stopped at $(date) ==="
exit 1
