#!/bin/bash

# ralph.sh - Autonomous codebase maintenance and documentation sync
# Combines code quality fixes (Part A) and documentation sync (Part B)
# into a single workflow. Each task is completed by one Claude CLI invocation.
#
# Usage:
#   ./scripts/ralph.sh              # Run all 31 tasks (maintenance + docs)
#   ./scripts/ralph.sh maintenance  # Run 13 maintenance tasks only
#   ./scripts/ralph.sh docs         # Run 18 doc sync tasks only
#
# Replaces: ralph-maintenance.sh + ralph-docs.sh

set -e

MODE="${1:-all}"

# Validate mode
case "$MODE" in
  all|maintenance|docs) ;;
  *)
    echo "Usage: $0 [all|maintenance|docs]"
    echo ""
    echo "  all          Run all 31 tasks (maintenance + docs) [default]"
    echo "  maintenance  Run 13 code quality tasks only"
    echo "  docs         Run 18 documentation sync tasks only"
    exit 1
    ;;
esac

# ============================================================
# Configuration
# ============================================================

CHECKLIST_FILE="ralph-checklist.md"
LOG_DIR="logs/maintenance"
MAX_ITERATIONS=45

mkdir -p "$LOG_DIR"

# ============================================================
# Shared Functions
# ============================================================

log() {
  echo "$@" | tee -a "$LOG_FILE"
}

setup_branch() {
  if [ -f "$CHECKLIST_FILE" ]; then
    if grep -q "^\- \[ \]" "$CHECKLIST_FILE" && ! grep -q "ALL_TASKS_DONE" "$CHECKLIST_FILE"; then
      EXISTING_BRANCH=$(git branch --show-current)
      if [[ "$EXISTING_BRANCH" == ralph/* ]] || [[ "$EXISTING_BRANCH" == maintenance/* ]] || [[ "$EXISTING_BRANCH" == docs-sync/* ]]; then
        echo "Resuming on existing branch: $EXISTING_BRANCH"
        BRANCH_NAME="$EXISTING_BRANCH"
        LOG_FILE="$LOG_DIR/$(echo "$BRANCH_NAME" | tr '/' '-').log"
        echo "=== Resuming at $(date) ===" >> "$LOG_FILE"
        return 0
      else
        echo "Found incomplete checklist but not on a ralph/ branch."
        echo "Current branch: $EXISTING_BRANCH"
        echo "Options:"
        echo "  1) Delete $CHECKLIST_FILE and start fresh"
        echo "  2) Checkout the correct branch and re-run"
        exit 1
      fi
    else
      rm -f "$CHECKLIST_FILE"
    fi
  fi

  BRANCH_NAME="ralph/$(date +%Y%m%d-%H%M%S)"
  LOG_FILE="$LOG_DIR/$(echo "$BRANCH_NAME" | tr '/' '-').log"
  git checkout -b "$BRANCH_NAME"
  echo "Starting on branch: $BRANCH_NAME"
  echo "=== Started at $(date) ===" > "$LOG_FILE"
}

check_completion() {
  grep -q "ALL_TASKS_DONE" "$CHECKLIST_FILE" 2>/dev/null
}

create_pr() {
  log ""
  log "All tasks complete! Pushing branch and creating PR..."
  git push -u origin "$BRANCH_NAME"

  local title body
  case "$MODE" in
    all)         title="Maintenance + Docs: Automated quality improvements and doc sync" ;;
    maintenance) title="Maintenance: Automated code quality improvements" ;;
    docs)        title="Docs: Sync all documentation with current codebase" ;;
  esac

  gh pr create --title "$title" --body "$(cat <<'PREOF'
## Automated Maintenance & Documentation Sync

Generated by `scripts/ralph.sh`.

### Part A: Code Quality
- Lint and type check fixes
- Test coverage improvements
- Dead code removal
- Dependency vulnerability patches
- Version and registration consistency

### Part B: Documentation Sync
- Synced all doc files against actual codebase state
- Updated CLI, MCP, and agent references
- Regenerated llms.txt manifests and mdBook output
- Fixed stale references and broken links

### Review Notes
- Each change committed separately for easy review
- All checks pass locally (`./scripts/check.sh`)
- See `ralph-checklist.md` for detailed progress log

---
Generated by scripts/ralph.sh
PREOF
)"
  log "PR created on branch: $BRANCH_NAME"
}

# ============================================================
# Checklist Generation
# ============================================================

generate_checklist() {
  [ -f "$CHECKLIST_FILE" ] && return 0  # Resume: don't overwrite

  cat > "$CHECKLIST_FILE" << 'HEADER'
# Ralph Checklist

Automated codebase maintenance and documentation sync for pretorin-cli.

HEADER

  if [ "$MODE" = "all" ] || [ "$MODE" = "maintenance" ]; then
    cat >> "$CHECKLIST_FILE" << 'MAINT'
## Part A: Code Quality

### Analysis & Quick Fixes

- [ ] **A1. CI Health Check** - Review recent GitHub Actions runs, identify existing failures to fix
- [ ] **A2. Lint Fixes** - Run ruff check + format, auto-fix what's possible, document remaining issues
- [ ] **A3. Type Check Fixes** - Run mypy, fix type errors in critical paths (client, MCP handlers, CLI)
- [ ] **A4. TODO/FIXME Audit** - Catalog all TODO/FIXME comments, resolve quick ones, create issues for complex ones

### Test Quality

- [ ] **A5. Test Coverage Analysis** - Identify files <60% coverage, write missing tests for critical code (client, attestation, MCP handlers)
- [ ] **A6. Dead Test Cleanup** - Find and remove tests for deleted features/code, fix flaky tests

### Code Quality

- [ ] **A7. Code Duplication Audit** - Find redundant utilities, similar handler patterns, copy-paste code across CLI/MCP/agent surfaces
- [ ] **A8. Dead Code Removal** - Find unused imports, functions, models, CLI commands. Remove them.
- [ ] **A9. Dependency Updates** - Check for outdated or vulnerable dependencies, update safe ones, document risky ones

### Release & Config Health

- [ ] **A10. Version Consistency** - Verify pyproject.toml version == __init__.py __version__ == CHANGELOG.md latest heading. Fix drift.
- [ ] **A11. MCP Tool Registration Audit** - Verify every Tool in tools.py has a handler in __init__.py and vice versa. Flag orphans.
- [ ] **A12. Agent Skill Tool Coverage** - Verify agent skills reference tools that actually exist in agent/tools.py. Flag stale references.

### Maintenance Verification

- [ ] **A13. Maintenance Verification** - Run `./scripts/check.sh` locally (lint, typecheck, all tests). If it passes, mark complete. Do NOT push, create a PR, or run CI — the outer script handles that.

MAINT
  fi

  if [ "$MODE" = "all" ] || [ "$MODE" = "docs" ]; then
    cat >> "$CHECKLIST_FILE" << 'DOCS'
## Part B: Documentation Sync

### Standalone Docs

- [ ] **B1. README.md Sync** - Verify README matches current feature set, install instructions, version, and quick-start commands. Update stale sections.
- [ ] **B2. CLI.md Sync** - Read all typer commands in src/pretorin/cli/, compare against docs/CLI.md. Update command tables, examples, flags, and workflow descriptions.
- [ ] **B3. MCP.md Sync** - Read all MCP tools in src/pretorin/mcp/tools.py and handlers, compare against docs/MCP.md. Update tool tables, parameters, examples, and tool counts.

### mdBook Core Reference

- [ ] **B4. Introduction & Getting Started** - Verify docs/src/introduction.md, installation.md, authentication.md, quickstart.md match current install flow, auth setup, and first-run experience.
- [ ] **B5. CLI Command Reference** - Read src/pretorin/cli/ and compare against docs/src/cli/command-reference.md. Verify every command, subcommand, flag, and argument is documented. Add missing commands, remove stale ones.
- [ ] **B6. CLI Feature Pages** - Read each CLI module and update the corresponding docs/src/cli/ page. Verify examples work.
- [ ] **B7. MCP Tool Reference** - Read src/pretorin/mcp/tools.py and compare against docs/src/mcp/tools.md. Verify every tool, parameter, and description matches. Update tool counts.
- [ ] **B8. MCP Setup & Overview** - Verify docs/src/mcp/overview.md, setup.md, resources.md, troubleshooting.md match current MCP server behavior, config format, and resource URIs.

### Agent & Framework Docs

- [ ] **B9. Agent Docs** - Read src/pretorin/agent/ (tools.py, skills.py, runtime.py) and update docs/src/agent/ pages. Verify skill names, tool lists, and runtime behavior match code.
- [ ] **B10. Framework Docs** - Verify docs/src/frameworks/ pages match the current framework catalog. Check framework counts and ID format examples against actual data.

### Workflow Docs

- [ ] **B11. Workflow Pages** - Read src/pretorin/cli/ workflow commands and compare against docs/src/workflows/ pages. Update workflows that have changed.
- [ ] **B12. Changelog Sync** - Verify docs/src/reference/changelog.md matches CHANGELOG.md content. Ensure the latest version entry is present.
- [ ] **B13. Environment Variables** - Read all env var references in src/pretorin/ and compare against docs/src/reference/environment.md. Add missing vars, remove stale ones.

### Generated Artifacts & Cross-references

- [ ] **B14. llms.txt Manifests** - Regenerate docs/llms.txt and docs/llms-full.txt from current docs/src/ content. Verify they match the SUMMARY.md structure.
- [ ] **B15. mdBook Build** - Run ./scripts/build-docs.sh to rebuild docs/book/ from docs/src/. Commit any changes to generated output.
- [ ] **B16. Dead Doc Detection** - Find docs referencing deleted CLI commands, removed MCP tools, old env vars, or nonexistent file paths. Fix or remove stale content.
- [ ] **B17. Cross-reference Validation** - Verify all internal markdown links in docs/src/ resolve to real files. Fix broken links. Check SUMMARY.md entries all point to existing pages.
- [ ] **B18. Final Verification** - Run `./scripts/check.sh` to ensure no changes broke anything. If it passes, mark complete. Do NOT push, create a PR, or run CI — the outer script handles that.

DOCS
  fi

  cat >> "$CHECKLIST_FILE" << 'FOOTER'
## Progress Log

FOOTER
  log "Created $CHECKLIST_FILE (mode: $MODE)"
}

# ============================================================
# Claude Prompt
# ============================================================

build_prompt() {
  local prompt="@$CHECKLIST_FILE

You are an autonomous engineer maintaining pretorin-cli, a Python CLI and MCP server for compliance automation. You handle both CODE QUALITY fixes (Part A) and DOCUMENTATION SYNC (Part B).

Branch: $BRANCH_NAME

CRITICAL: Complete exactly ONE task, commit your changes, then output <promise>DONE</promise> and stop.

## PROJECT STRUCTURE

Source code:
- src/pretorin/cli/ — typer CLI commands (main.py registers all subcommands)
- src/pretorin/mcp/tools.py — MCP tool definitions (Tool objects with inputSchema)
- src/pretorin/mcp/handlers/ — MCP tool handler implementations
- src/pretorin/mcp/handlers/__init__.py — TOOL_HANDLERS dispatch dict
- src/pretorin/agent/tools.py — agent tool definitions
- src/pretorin/agent/skills.py — agent skill definitions with tool_names lists
- src/pretorin/client/api.py — PretorianClient API methods
- src/pretorin/attestation.py — source attestation and verification
- src/pretorin/__init__.py — __version__ string

Documentation:
- README.md — top-level project overview
- docs/CLI.md — standalone CLI reference (detailed, with examples)
- docs/MCP.md — standalone MCP reference (detailed, with examples)
- docs/src/ — mdBook source files
- docs/src/SUMMARY.md — mdBook table of contents
- docs/src/cli/ — CLI feature pages and command reference
- docs/src/mcp/ — MCP overview, setup, tools, resources, troubleshooting
- docs/src/agent/ — agent overview, skills, runtime
- docs/src/frameworks/ — supported frameworks, control ID formats
- docs/src/workflows/ — workflow guides
- docs/src/reference/ — env vars, changelog, contributing, artifact schema
- docs/src/getting-started/ — install, auth, quickstart
- docs/book/ — generated mdBook output (rebuild with ./scripts/build-docs.sh)
- docs/llms.txt — LLM-friendly doc manifest
- docs/llms-full.txt — full LLM doc manifest

Config & metadata:
- pyproject.toml — package version, dependencies
- CHANGELOG.md — release history
- .github/workflows/test.yml — CI pipeline
- ./scripts/check.sh — local verification script

## TOOLS REFERENCE

**Linting & Types:**
- uv run ruff check src/pretorin --fix
- uv run ruff format src/pretorin
- uv run mypy src/pretorin

**Tests:**
- uv run pytest -v --cov=pretorin --cov-report=term-missing -q
- uv run pytest tests/test_specific_file.py -v

**Code Analysis:**
- grep -rn 'TODO\|FIXME' src/pretorin/ tests/ | head -50
- grep -rn 'import.*unused' src/pretorin/ (after ruff)

**Version Consistency:**
- grep 'version' pyproject.toml | head -3
- grep '__version__' src/pretorin/__init__.py
- head -20 CHANGELOG.md

**MCP Tool Registration:**
- grep 'name=\"pretorin_' src/pretorin/mcp/tools.py (all defined tools)
- grep 'pretorin_' src/pretorin/mcp/handlers/__init__.py (all registered handlers)

**Agent Skills:**
- grep -A 20 'tool_names' src/pretorin/agent/skills.py (tools referenced by skills)
- grep 'name=\"' src/pretorin/agent/tools.py (tools actually defined)

**Dependencies:**
- uv run pip-audit --skip-editable .
- uv pip list --outdated

**CI:**
- gh run list --limit 5
- gh run view <id> --log-failed

**Docs Build:**
- ./scripts/build-docs.sh

**Local Verification:**
- ./scripts/check.sh

## PART A: CODE QUALITY GUIDANCE

(Follow this section when the current task starts with A)

**A1 CI Health Check:** Run gh run list --limit 5. If failures exist, investigate with gh run view <id> --log-failed. Log findings.
**A2 Lint Fixes:** Run uv run ruff check src/pretorin --fix && uv run ruff format src/pretorin. For remaining issues, fix manually if simple.
**A3 Type Check Fixes:** Run uv run mypy src/pretorin. Focus on errors in client/, mcp/, cli/. Skip complex generic issues.
**A4 TODO/FIXME:** Quick fixes (<10 lines): just do them. Complex ones: leave a note in checklist.
**A5 Test Coverage:** Run uv run pytest --cov=pretorin --cov-report=term-missing -q. Focus on business logic. Write meaningful tests, not coverage padding.
**A6 Dead Test Cleanup:** Look for tests referencing removed functions/classes. Remove them. Run tests after.
**A7 Code Duplication:** Look for similar patterns across CLI/MCP/agent surfaces. Extract shared logic if it reduces maintenance burden.
**A8 Dead Code:** Use ruff to find unused imports. Search for unreferenced functions/classes. Remove and test.
**A9 Dependency Updates:** Run uv run pip-audit --skip-editable . for vulnerabilities. Check uv pip list --outdated. Only update safe ones.
**A10 Version Consistency:** Compare pyproject.toml version, __init__.py __version__, and CHANGELOG.md latest heading. All must match.
**A11 MCP Tool Registration:** Compare tool names in tools.py vs handler keys in handlers/__init__.py. Every tool needs a handler and vice versa.
**A12 Agent Skill Coverage:** Compare tool_names lists in skills.py against actual tool definitions in agent/tools.py. Flag references to nonexistent tools.
**A13 Maintenance Verification:** Run ./scripts/check.sh. Fix any failures caused by our changes.

Commit format: \"fix(maintenance): <what was fixed>\" or \"refactor(maintenance): <what changed>\"

## PART B: DOCUMENTATION SYNC GUIDANCE

(Follow this section when the current task starts with B)

### SOURCE OF TRUTH

**B1 README.md:** Read pyproject.toml (version, deps), src/pretorin/cli/main.py (command groups), src/pretorin/mcp/tools.py (tool count). Compare against README.md.
**B2 CLI.md:** Read every file in src/pretorin/cli/ for @app.command, typer.Argument, typer.Option. Compare against docs/CLI.md.
**B3 MCP.md:** Read src/pretorin/mcp/tools.py for Tool() definitions, handlers/__init__.py for TOOL_HANDLERS. Compare against docs/MCP.md.
**B4 Getting Started:** Read cli/auth.py, cli/main.py, client/config.py. Compare against docs/src/getting-started/ pages.
**B5 CLI Command Reference:** Read src/pretorin/cli/ and compare against docs/src/cli/command-reference.md. Every @app.command needs a row.
**B6 CLI Feature Pages:** For each docs/src/cli/<feature>.md, read the corresponding src/pretorin/cli/<module>.py. Verify examples and flags.
**B7 MCP Tool Reference:** Read src/pretorin/mcp/tools.py tool by tool. Compare against docs/src/mcp/tools.md.
**B8 MCP Setup:** Verify docs/src/mcp/overview.md, setup.md, resources.md, troubleshooting.md match server behavior and resource URIs.
**B9 Agent Docs:** Read src/pretorin/agent/ (tools.py, skills.py, runtime.py). Compare against docs/src/agent/ pages.
**B10 Framework Docs:** Verify docs/src/frameworks/ pages. Check framework counts and ID format examples.
**B11 Workflow Pages:** Read CLI workflow commands. Compare against docs/src/workflows/ descriptions and examples.
**B12 Changelog:** Diff CHANGELOG.md against docs/src/reference/changelog.md.
**B13 Environment Variables:** grep -rn 'os.environ\|os.getenv\|PRETORIN_' src/pretorin/. Compare against docs/src/reference/environment.md.
**B14 llms.txt:** Read SUMMARY.md. Regenerate docs/llms.txt and docs/llms-full.txt following existing format.
**B15 mdBook Build:** Run ./scripts/build-docs.sh. Commit any changes to docs/book/.
**B16 Dead Doc Detection:** Verify every CLI command, MCP tool, and env var mentioned in docs still exists in source. Fix stale references.
**B17 Cross-reference Validation:** Verify all markdown links in docs/src/ resolve. Fix broken links. Check SUMMARY.md entries.
**B18 Final Verification:** Run ./scripts/check.sh. Fix any failures.

Commit format: \"docs(<scope>): <what was updated>\"

## RULES

1. **DO ONE TASK ONLY** - Complete exactly one checklist item per iteration
2. **READ BEFORE WRITING** - Always read actual code/doc files before making changes. Never guess.
3. **ACTUALLY FIX ISSUES** - Don't just report them. Write code, update docs, delete dead content.
4. **BE CONSERVATIVE** - If a fix is risky, note it in the checklist and skip.
5. **RUN TESTS** - Before committing: uv run pytest -x -q
6. **COMMIT EACH CHANGE** - Use descriptive commit messages with the appropriate format above.
7. **UPDATE CHECKLIST** - Mark [x] complete, add log entry with commit hash and brief summary.
8. **STOP AFTER ONE** - Output <promise>DONE</promise> and STOP IMMEDIATELY.

## WORKFLOW

1. Read checklist, find first unchecked [ ] task
2. Determine if it's Part A (code quality) or Part B (docs sync)
3. Follow the corresponding guidance section above
4. Make changes, run tests, commit
5. Update checklist: mark [x], add log entry with timestamp + commit hash
6. Output <promise>DONE</promise>
7. STOP IMMEDIATELY

When ALL tasks are [x] complete, add 'ALL_TASKS_DONE' at the end of the checklist."

  echo "$prompt"
}

# ============================================================
# Main
# ============================================================

setup_branch
generate_checklist

echo ""
echo "Starting ralph ($MODE mode)..."
echo "Checklist: $CHECKLIST_FILE"
echo "Branch:    $BRANCH_NAME"
echo "Log:       $LOG_FILE"
echo ""

ITERATION=0

while [ $ITERATION -lt $MAX_ITERATIONS ]; do
  ITERATION=$((ITERATION + 1))
  log ""
  log "=== Iteration $ITERATION of $MAX_ITERATIONS at $(date) ==="

  if check_completion; then
    create_pr
    log "=== Completed at $(date) ==="
    exit 0
  fi

  set +e
  OUTPUT=$(claude --dangerously-skip-permissions -p "$(build_prompt)")
  CLAUDE_EXIT_CODE=$?
  set -e

  echo "$OUTPUT" | tee -a "$LOG_FILE"

  if [ $CLAUDE_EXIT_CODE -ne 0 ]; then
    log ""
    log "WARNING: Claude exited with code $CLAUDE_EXIT_CODE"
    if check_completion; then
      log "Tasks complete despite error. Proceeding..."
      continue
    fi
    log "Waiting before retry..."
    sleep 5
    continue
  fi

  if echo "$OUTPUT" | grep -q "<promise>DONE</promise>"; then
    log "--- Task completed, restarting with fresh context ---"
  else
    log "WARNING: No completion marker found"
  fi

  sleep 2
done

log ""
log "Reached max iterations ($MAX_ITERATIONS)."
log "Check $CHECKLIST_FILE for remaining tasks."
log "Re-run the script to resume."
log "=== Stopped at $(date) ==="
exit 1
