"""MCP tool handler dispatch table."""

from __future__ import annotations

from collections.abc import Awaitable, Callable
from typing import Any

from mcp.types import CallToolResult, TextContent

from pretorin.client import PretorianClient
from pretorin.mcp.handlers.compliance import (
    handle_add_control_note,
    handle_generate_control_artifacts,
    handle_get_control_context,
    handle_get_control_implementation,
    handle_get_control_notes,
    handle_get_org_policy_questionnaire,
    handle_get_scope,
    handle_list_org_policies,
    handle_patch_org_policy_qa,
    handle_patch_scope_qa,
    handle_push_monitoring_event,
    handle_resolve_control_note,
    handle_update_control_status,
    handle_update_narrative,
)
from pretorin.mcp.handlers.evidence import (
    handle_create_evidence,
    handle_create_evidence_batch,
    handle_get_narrative,
    handle_link_evidence,
    handle_search_evidence,
)
from pretorin.mcp.handlers.frameworks import (
    handle_get_control,
    handle_get_control_references,
    handle_get_controls_batch,
    handle_get_document_requirements,
    handle_get_framework,
    handle_list_control_families,
    handle_list_controls,
    handle_list_frameworks,
)
from pretorin.mcp.handlers.stig import (
    handle_get_cci,
    handle_get_cci_chain,
    handle_get_cci_status,
    handle_get_stig,
    handle_get_stig_applicability,
    handle_get_stig_rule,
    handle_get_test_manifest,
    handle_infer_stigs,
    handle_list_ccis,
    handle_list_stig_rules,
    handle_list_stigs,
    handle_submit_test_results,
)
from pretorin.mcp.handlers.systems import (
    handle_get_cli_status,
    handle_get_compliance_status,
    handle_get_source_manifest,
    handle_get_system,
    handle_list_systems,
)
from pretorin.mcp.handlers.vendors import (
    handle_create_vendor,
    handle_delete_vendor,
    handle_generate_inheritance_narrative,
    handle_get_control_responsibility,
    handle_get_stale_edges,
    handle_get_vendor,
    handle_link_evidence_to_vendor,
    handle_list_vendor_documents,
    handle_list_vendors,
    handle_remove_control_responsibility,
    handle_set_control_responsibility,
    handle_sync_stale_edges,
    handle_update_vendor,
    handle_upload_vendor_document,
)
from pretorin.mcp.handlers.workflow import (
    handle_answer_policy_question,
    handle_answer_scope_question,
    handle_apply_campaign,
    handle_claim_campaign_items,
    handle_get_analytics_summary,
    handle_get_campaign_item_context,
    handle_get_campaign_status,
    handle_get_family_analytics,
    handle_get_family_bundle,
    handle_get_family_review_results,
    handle_get_pending_families,
    handle_get_pending_policy_questions,
    handle_get_pending_scope_questions,
    handle_get_policy_analytics,
    handle_get_policy_question_detail,
    handle_get_policy_review_results,
    handle_get_policy_workflow_state,
    handle_get_scope_question_detail,
    handle_get_scope_review_results,
    handle_get_workflow_state,
    handle_prepare_campaign,
    handle_submit_campaign_proposal,
    handle_trigger_family_review,
    handle_trigger_policy_generation,
    handle_trigger_policy_review,
    handle_trigger_scope_generation,
    handle_trigger_scope_review,
)

ToolHandler = Callable[[PretorianClient, dict[str, Any]], Awaitable[list[TextContent] | CallToolResult]]

TOOL_HANDLERS: dict[str, ToolHandler] = {
    "pretorin_list_frameworks": handle_list_frameworks,
    "pretorin_get_framework": handle_get_framework,
    "pretorin_list_control_families": handle_list_control_families,
    "pretorin_list_controls": handle_list_controls,
    "pretorin_get_control": handle_get_control,
    "pretorin_get_controls_batch": handle_get_controls_batch,
    "pretorin_get_control_references": handle_get_control_references,
    "pretorin_get_document_requirements": handle_get_document_requirements,
    "pretorin_list_systems": handle_list_systems,
    "pretorin_get_cli_status": handle_get_cli_status,
    "pretorin_get_source_manifest": handle_get_source_manifest,
    "pretorin_get_system": handle_get_system,
    "pretorin_get_compliance_status": handle_get_compliance_status,
    "pretorin_search_evidence": handle_search_evidence,
    "pretorin_create_evidence": handle_create_evidence,
    "pretorin_create_evidence_batch": handle_create_evidence_batch,
    "pretorin_link_evidence": handle_link_evidence,
    "pretorin_get_narrative": handle_get_narrative,
    "pretorin_generate_control_artifacts": handle_generate_control_artifacts,
    "pretorin_push_monitoring_event": handle_push_monitoring_event,
    "pretorin_add_control_note": handle_add_control_note,
    "pretorin_resolve_control_note": handle_resolve_control_note,
    "pretorin_get_control_notes": handle_get_control_notes,
    "pretorin_update_control_status": handle_update_control_status,
    "pretorin_get_control_implementation": handle_get_control_implementation,
    "pretorin_get_control_context": handle_get_control_context,
    "pretorin_get_scope": handle_get_scope,
    "pretorin_patch_scope_qa": handle_patch_scope_qa,
    "pretorin_list_org_policies": handle_list_org_policies,
    "pretorin_get_org_policy_questionnaire": handle_get_org_policy_questionnaire,
    "pretorin_patch_org_policy_qa": handle_patch_org_policy_qa,
    "pretorin_update_narrative": handle_update_narrative,
    # Agentic Workflow Tools
    "pretorin_get_workflow_state": handle_get_workflow_state,
    "pretorin_get_pending_scope_questions": handle_get_pending_scope_questions,
    "pretorin_get_scope_question_detail": handle_get_scope_question_detail,
    "pretorin_answer_scope_question": handle_answer_scope_question,
    "pretorin_trigger_scope_generation": handle_trigger_scope_generation,
    "pretorin_trigger_scope_review": handle_trigger_scope_review,
    "pretorin_get_scope_review_results": handle_get_scope_review_results,
    "pretorin_get_pending_policy_questions": handle_get_pending_policy_questions,
    "pretorin_get_policy_question_detail": handle_get_policy_question_detail,
    "pretorin_answer_policy_question": handle_answer_policy_question,
    "pretorin_trigger_policy_generation": handle_trigger_policy_generation,
    "pretorin_trigger_policy_review": handle_trigger_policy_review,
    "pretorin_get_policy_review_results": handle_get_policy_review_results,
    "pretorin_get_policy_workflow_state": handle_get_policy_workflow_state,
    "pretorin_get_pending_families": handle_get_pending_families,
    "pretorin_get_family_bundle": handle_get_family_bundle,
    "pretorin_trigger_family_review": handle_trigger_family_review,
    "pretorin_get_family_review_results": handle_get_family_review_results,
    "pretorin_get_analytics_summary": handle_get_analytics_summary,
    "pretorin_get_family_analytics": handle_get_family_analytics,
    "pretorin_get_policy_analytics": handle_get_policy_analytics,
    "pretorin_prepare_campaign": handle_prepare_campaign,
    "pretorin_claim_campaign_items": handle_claim_campaign_items,
    "pretorin_get_campaign_item_context": handle_get_campaign_item_context,
    "pretorin_submit_campaign_proposal": handle_submit_campaign_proposal,
    "pretorin_apply_campaign": handle_apply_campaign,
    "pretorin_get_campaign_status": handle_get_campaign_status,
    # Vendor Management Tools
    "pretorin_list_vendors": handle_list_vendors,
    "pretorin_create_vendor": handle_create_vendor,
    "pretorin_get_vendor": handle_get_vendor,
    "pretorin_update_vendor": handle_update_vendor,
    "pretorin_delete_vendor": handle_delete_vendor,
    "pretorin_upload_vendor_document": handle_upload_vendor_document,
    "pretorin_list_vendor_documents": handle_list_vendor_documents,
    "pretorin_link_evidence_to_vendor": handle_link_evidence_to_vendor,
    "pretorin_get_control_responsibility": handle_get_control_responsibility,
    "pretorin_set_control_responsibility": handle_set_control_responsibility,
    "pretorin_remove_control_responsibility": handle_remove_control_responsibility,
    "pretorin_get_stale_edges": handle_get_stale_edges,
    "pretorin_sync_stale_edges": handle_sync_stale_edges,
    "pretorin_generate_inheritance_narrative": handle_generate_inheritance_narrative,
    # STIG / CCI Tools
    "pretorin_list_stigs": handle_list_stigs,
    "pretorin_get_stig": handle_get_stig,
    "pretorin_list_stig_rules": handle_list_stig_rules,
    "pretorin_get_stig_rule": handle_get_stig_rule,
    "pretorin_list_ccis": handle_list_ccis,
    "pretorin_get_cci": handle_get_cci,
    "pretorin_get_cci_chain": handle_get_cci_chain,
    "pretorin_get_test_manifest": handle_get_test_manifest,
    "pretorin_submit_test_results": handle_submit_test_results,
    "pretorin_get_stig_applicability": handle_get_stig_applicability,
    "pretorin_get_cci_status": handle_get_cci_status,
    "pretorin_infer_stigs": handle_infer_stigs,
}
